# Generated by Django 3.2 on 2022-01-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220116_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storie',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='storie',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
