# Generated by Django 3.2 on 2022-05-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storie',
            name='excerpt',
        ),
    ]
