# Generated by Django 3.2 on 2022-05-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_alter_poststorie_posted_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poststorie',
            name='meta_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
